---
- name: 'Install Template: Direct Access - Route Up'
  template: >
   src=vpn-route-up.bash.j2
   dest='{{ openvpn_route_up.1 }}'
   backup=no
   force=yes
   owner={{ openvpn_owner }}
   group={{ openvpn_group }}
   mode=0700
  when: openvpn_route_up is defined and openvpn_route_up.0 == 'template' and openvpn_route_up.1 is defined

- name: 'Copy Program: Route Up'
  copy: >
   src=openvpn_route_up.0
   dest=openvpn_route_up.1
   backup=no
   follow=yes
   force=yes
   owner={{ openvpn_owner }}
   group={{ openvpn_group }}
   mode=0700
  when: openvpn_route_up is defined and (openvpn_route_up.0 != '' and openvpn_route_up.0 != 'template') and openvpn_route_up.1 is defined
